name: distill_resnet
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - scikit-learn
  - matplotlib
  - tqdm
  - optuna
  - pip
  - pip:
      - wandb
